update: instructions configuration template to imx8qm
tiiuae/build-configurations pull request #5
Opened 2022-12-12 14:19 UTC by vilvo

* as there is currently no other configuration, let's use imx8qm-config.nix instead of abstract template config.  It's easier for users to copy-paste to shell.

2022-12-12 14:25 UTC, vilvo commented
Generic comments for improving the documentation from user perspective.
1. Better instruct user with commands that user can just copy-paste to reproduce the image.
2. When we have more configs, I'd prefer table for the explicit build commands for supported configs instead of <template> user is required to change.
3. flake.nix with different targets - like `nix build .#imx8qm` would be be preferred development. The dependency repositories can be included inside the flake.nix and make the build reproducible. And more simple from the user perspective.
FYI @jenninikko @remimimimimi

2022-12-12 14:44 UTC, unbel13ver commented
@vilvo please check my latest push to the PR#3
Particularly this: https://github.com/tiiuae/build-configurations/pull/3/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R22

2022-12-12 17:38 UTC, ktusawrk commented
I agree that the build instructions should be possible to copy-paste from the instructions to the command line. If there are more than one configuration available, explanatory heading or text before each complete copy-pasteable command can be added.

2022-12-13 06:37 UTC, vilvo commented
> @vilvo please check my latest push to the PR#3 Particularly this: https://github.com/tiiuae/build-configurations/pull/3/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R22

https://github.com/tiiuae/build-configurations/pull/3/files#r1046710175

2022-12-15 06:58 UTC, vilvo commented
@unbel13ver @tervis-unikie ping for review

2022-12-15 07:12 UTC, tervis-unikie requested changes
Please format commit message according to our commit message guidelines.

2022-12-15 11:13 UTC, tervis-unikie approved these changes

2022-12-15 11:54 UTC, merged